### ISSUE TITLE
Vertical swipe not working properly

### ISSUE THREAD

**Issue by ketanahir** [mohitsvnit/Vertical-ViewPager-Horizontal-ViewPager-Android#1]
Thanks for the great library.
I am facing issue with vertical swiping. Some times it works but when I try swipe vertical from upper part of the screen it stuck. Do you have any idea how to solve this and make it smoother?

**Comment by mohitsvnit** [comment]
I am glad that people are using it and finding it help full.

I created it more smoother but didn't updated it. I will update it soon as I know that people are using it. Please give it a star if you like it. 

About your query, you have to modify swapXY function in vertical viewpager class. There we are converting horizontal movement to vertical movement.

As our screen height is almost double of width, swiping vertically is not as smooth as swiping it horizontally.

I don't exactly remember what I chabged in that method and right now I am unable to change for few days. I will update it in next week.

**Comment by ketanahir** [comment]
Can you find some time to update or suggest me what should I change?

**Comment by mohitsvnit** [comment]
@ketanahir I updated the code. Please try it and give a review.

**Comment by ZalaJanaksinh** [comment]
If I added vertical view pager inside horizontal  then horizontal swipe not working. could please guide me.
I do reverse thing as you do.

**Comment by mohitsvnit** [comment]
you can do that. It should work fine.
Please add it as another issue. I am closing this issue as it is solved.
