### ISSUE TITLE
Not able to get correct index for Horizontal Swipe layout

### ISSUE THREAD

**Issue by pixy0403** [mohitsvnit/Vertical-ViewPager-Horizontal-ViewPager-Android#2]
Hi, I wish to load a different layout on horizontal swipe but not able to get correct position to make changes in horizontal swipe change. Please help me out

**Comment by mohitsvnit** [comment]
Can you please elaborate your issue. Would like to help.

**Comment by pixy0403** [comment]
Sure and thanks, I have to show some other layout when swapping horizontally, though I am able to do this in vertical swapping but no idea in horizontal.

Are you still there? :(

**Comment by pixy0403** [comment]
Hi was waiting for any sort of reply from your side

**Comment by mohitsvnit** [comment]
lets solve it now. Can you describe it in more details. I am still unable to get your problem.

**Comment by pixy0403** [comment]
How to set some other fragment for horizontal swipes

**Comment by mohitsvnit** [comment]
currently 3 fragments are supported in horizontal swipe. You want to add more right?

**Comment by mohitsvnit** [comment]
You can change the number return by `getCount` function to change number of horizontal fragments. 
[Here](https://github.com/mohitsvnit/Vertical-ViewPager-Horizontal-ViewPager-Android/blob/610321f012bbf9c7100ceb11420d58fa92478c9f/app/src/main/java/com/mohit/verticalviewpager/HorizontalViewPagerAdapter.java#L36)

**Comment by pixy0403** [comment]
No currently both vertical n horizontal swipes are using single same layout i just want to use different layout XML for vertical and horizontal fragment s respectively

**Comment by mohitsvnit** [comment]
ok got it. You can use different layout. You can see that in `HorizontalViewPagerAdapter` and `VerticalViewPagerAdapter`, `getItem` method is returning instance of `ChildFragment` class. You can create separate class for each type of pager, to use different layout.

**Comment by pixy0403** [comment]
I have created two different fragment for each vertical and horizontal adapters. But when I run the code it only shows layout from horizontal layout fragmne

**Comment by mohitsvnit** [comment]
Show me the code

**Comment by pixy0403** [comment]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        callVewscreen();
    }

**Comment by pixy0403** [comment]
public class HorizontalContentFragment extends Fragment {
    public TextView text;
    public ImageView newsImg;
    int[] myImageList = new int[]{R.drawable.news_1, R.drawable.news_2,R.drawable.news_3};
    public HorizontalContentFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_hori_child, container, false);
        // Inflate the layout for this fragment
        text = (TextView) view.findViewById(R.id.child);
        newsImg = (ImageView) view.findViewById(R.id.newsImg);
        // tvChild = (TextView) view.findViewById(R.id.tvChild);
        Bundle bundle = getArguments();
        Log.e("Child INDEX",""+bundle.getString("child"));
        Log.e("Parent INDEX",""+bundle.getString("parent"));
        if(bundle.getString("parent").equals("0")||bundle.getString("parent").equals("3")||
                bundle.getString("parent").equals("6")||bundle.getString("parent").equals("9")
                &&((bundle.getString("child")).equals("1"))){
            newsImg.setImageResource(myImageList[0]);
            text.setVisibility(View.GONE);
        }
        else   if(bundle.getString("parent").equals("1")||bundle.getString("parent").equals("4")||
                bundle.getString("parent").equals("7")&&((bundle.getString("child")).equals("1"))){
            newsImg.setImageResource(myImageList[1]);
            text.setVisibility(View.GONE);
        }
        else   if(bundle.getString("parent").equals("2")||bundle.getString("parent").equals("5")||
                bundle.getString("parent").equals("8")&&((bundle.getString("child")).equals("1"))){
            newsImg.setImageResource(myImageList[2]);
            text.setVisibility(View.GONE);
        }


   else if(((bundle.getString("child")).equals("0"))||((bundle.getString("child")).equals("2"))){

            newsImg.setVisibility(View.GONE);
            text.setText("CHILD ID IS->"+(bundle.getString("child")).equals("1"));
        }

        return view;
    }

}

**Comment by pixy0403** [comment]
public class ChildFragment extends Fragment {
    public ImageView newsImg;
    int[] myImageList = new int[]{R.drawable.news_1, R.drawable.news_2,R.drawable.news_3};
    public ChildFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_child, container, false);
        // Inflate the layout for this fragment
        newsImg = (ImageView) view.findViewById(R.id.newsImg);
       // tvChild = (TextView) view.findViewById(R.id.tvChild);
        Bundle bundle = getArguments();
        Log.e("Child INDEX",""+bundle.getString("child"));
        Log.e("Parent INDEX",""+bundle.getString("parent"));
        //tvParent.setText("Parent: " + bundle.getString("parent"));
       // tvChild.setText("Child: " + bundle.getString("child"));
if(bundle.getString("parent").equals("0")||bundle.getString("parent").equals("3")||
        bundle.getString("parent").equals("6")||bundle.getString("parent").equals("9")&&((bundle.getString("child")).equals("1"))){
    newsImg.setImageResource(myImageList[0]);
        }
     else   if(bundle.getString("parent").equals("1")||bundle.getString("parent").equals("4")||
                bundle.getString("parent").equals("7")){
            newsImg.setImageResource(myImageList[1]);
        }
else   if(bundle.getString("parent").equals("2")||bundle.getString("parent").equals("5")||
        bundle.getString("parent").equals("8")){
    newsImg.setImageResource(myImageList[2]);
}
else   if(bundle.getString("parent").equals("2")||bundle.getString("parent").equals("5")||
        bundle.getString("parent").equals("8")){
    newsImg.setImageResource(myImageList[2]);
}

else   if(bundle.getString("parent").equals("2")||bundle.getString("parent").equals("5")||
        bundle.getString("parent").equals("8")){
    newsImg.setImageResource(myImageList[2]);
}
        return view;
    }

  }

**Comment by pixy0403** [comment]
These two are for vertical and horizontal fragment respectively

**Comment by mohitsvnit** [comment]
No no. Show me your both adapter code and code where you are uaing those adapter.

**Comment by pixy0403** [comment]
if child id is 1 then vertical fragment's layout should only be shown for horizontal layout, but if child id is 0 or 2 then horizontal swipe views will be shown

**Comment by pixy0403** [comment]
public class HorizontalViewPagerAdapter extends FragmentStatePagerAdapter{

    public String parentId;

    public void setParentID(String parentID){
        this.parentId = parentID;
    }

    public HorizontalViewPagerAdapter(FragmentManager fm) {
        super(fm);
    }

    @Override
    public Fragment getItem(int position) {
        HorizontalContentFragment childFragment = new HorizontalContentFragment();

        //HorizontalContentFragment childFragment = new HorizontalContentFragment();
        Bundle bundle = new Bundle();
        bundle.putString("parent",parentId);
        bundle.putString("child",String.valueOf(position));
        childFragment.setArguments(bundle);
        return childFragment;
    }

    @Override
    public int getCount() {
        return 3;
    }
}

**Comment by pixy0403** [comment]
public class ViewPagerAdapter extends FragmentStatePagerAdapter {
    public ViewPagerAdapter(FragmentManager fm) {
        super(fm);
    }

    @Override
    public int getCount() {
        return 10;
    }

    @Override
    public Fragment getItem(int position) {
        ContentFragment contentFragment = new ContentFragment();
        Bundle bundle = new Bundle();
        bundle.putString("parent",String.valueOf(position));
        contentFragment.setArguments(bundle);
        return contentFragment;
    }
}

**Comment by pixy0403** [comment]
public class ContentFragment extends Fragment {

    public HorizontalViewPager viewPager;
    public HorizontalViewPagerAdapter horizontalViewPagerAdapter;
    public String parentInd;

    public ContentFragment() {
        // Required empty public constructor
    }
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_content, container, false);

        parentInd=getArguments().getString("parent");

        viewPager = (HorizontalViewPager) view.findViewById(R.id.vpHorizontal);
        horizontalViewPagerAdapter = new HorizontalViewPagerAdapter(getChildFragmentManager());
        horizontalViewPagerAdapter.setParentID(parentInd);
        viewPager.setAdapter(horizontalViewPagerAdapter);
        Helper.log("Card Created : " + parentInd);
        viewPager.setCurrentItem(1);
        return view;
    }

}

**Comment by mohitsvnit** [comment]
In your `horizontalviewpageradapter` `getitem` function, add if condition.
If position == 1:
    Return verticalviewpagerfragment
Else:
    Return horizontalviewpagerfragment

**Comment by pixy0403** [comment]
Thankyou so much

**Comment by mohitsvnit** [comment]
I am closing this issue.
